with descriptions (name_es, description_es, description_en) as (
  values
    ('Cuelgue Pasivo en Barra', 'Sujeta una barra con agarre firme y deja el cuerpo suspendido con brazos extendidos. Mantén el tronco estable, respira con normalidad y conserva un agarre seguro durante el tiempo indicado; evita balancearte, soltar bruscamente o continuar si aparece dolor en hombros o manos.', 'Grip a bar firmly and hang with your arms extended. Keep your torso steady, breathe normally, and maintain a secure grip for the prescribed time, avoiding swinging, suddenly releasing the bar, or continuing if shoulder or hand pain appears.'),
    ('Curl de Muñeca Pronado', 'Apoya los antebrazos sobre un banco o muslos con palmas hacia abajo y deja las manos fuera del borde. Eleva el dorso de las manos moviendo solo las muñecas, pausa y baja lentamente; usa poca carga y evita levantar los antebrazos o acelerar el recorrido.', 'Support your forearms on a bench or thighs with palms facing down and your hands beyond the edge. Raise the backs of your hands by moving only your wrists, pause, and lower slowly, using a light load and avoiding forearm lifting or rushed repetitions.'),
    ('Curl de Muñeca Supinado', 'Apoya los antebrazos con palmas hacia arriba y permite que las muñecas sobresalgan del banco o las rodillas. Flexiona las muñecas para acercar la carga, contrae los flexores y baja hasta un estiramiento cómodo; evita mover los codos, rebotar o usar un peso que limite el recorrido.', 'Support your forearms with palms facing up and let your wrists extend beyond the bench or knees. Curl the weight by flexing your wrists, squeeze the forearm flexors, and lower to a comfortable stretch without moving your elbows, bouncing, or using excessive load.'),
    ('Curl Alterno con Mancuernas', 'De pie o sentado, sostén las mancuernas a los lados con hombros estables. Flexiona un codo y gira gradualmente la palma hacia arriba, contrae el bíceps y baja antes de alternar; evita balancear el torso, adelantar el codo o dejar caer la carga.', 'Stand or sit with dumbbells at your sides and stable shoulders. Curl one arm while gradually turning the palm upward, squeeze the biceps, and lower before alternating, avoiding torso swing, forward elbow movement, or dropping the weight.'),
    ('Curl de Bíceps', 'De pie o sentado, mantén el pecho erguido y los codos junto al torso. Flexiona los codos llevando la carga hacia los hombros, aprieta el bíceps y baja lentamente hasta extender sin bloquear; evita balancearte, elevar los hombros o mover los brazos hacia adelante.', 'Stand or sit tall with your elbows beside your torso. Bend your elbows to bring the load toward your shoulders, squeeze your biceps, and lower slowly to near full extension without swinging, shrugging, or driving your upper arms forward.'),
    ('Curl de Bíceps con Barra', 'De pie, toma la barra con agarre supino al ancho de los hombros y mantén muñecas neutras. Flexiona los codos sin mover los brazos superiores, pausa cerca del pecho y baja con control; evita inclinar la espalda, usar impulso de cadera o separar los codos.', 'Stand with an underhand shoulder-width grip and neutral wrists. Curl the bar without moving your upper arms, pause near your chest, and lower under control, avoiding back lean, hip momentum, or flared elbows.'),
    ('Curl de Bíceps en Polea con Barra Recta', 'Frente a una polea baja, toma la barra con palmas hacia arriba y fija los codos junto al cuerpo. Flexiona hasta contraer el bíceps y regresa lentamente manteniendo tensión continua; evita inclinarte hacia atrás, doblar las muñecas o adelantar los hombros.', 'Face a low cable with an underhand grip and pin your elbows beside your body. Curl to contract your biceps and return slowly while maintaining continuous tension, avoiding backward lean, bent wrists, or forward shoulder movement.'),
    ('Curl de Bíceps Unilateral en Polea', 'Colócate frente a la polea baja y toma una manija con un brazo extendido. Mantén hombro y codo estables, flexiona hasta acercar la mano al hombro y vuelve lentamente; evita girar el tronco, inclinarte o acompañar el recorrido con todo el brazo.', 'Stand facing a low cable and hold one handle with your arm extended. Keep your shoulder and elbow stable, curl your hand toward your shoulder, and return slowly without rotating your torso, leaning, or moving the entire arm.'),
    ('Curl en Banco Inclinado con Mancuernas', 'Siéntate en un banco inclinado con espalda apoyada y brazos colgando a los lados. Mantén los hombros atrás, flexiona los codos y supina las manos, luego baja hasta un estiramiento controlado; evita adelantar los hombros o recortar el recorrido.', 'Sit on an incline bench with your back supported and arms hanging at your sides. Keep your shoulders back, curl and supinate your hands, then lower to a controlled stretch without rolling your shoulders forward or shortening the range.'),
    ('Curl en Banco Scott', 'Ajusta el banco para apoyar completamente la parte posterior de los brazos y toma una barra Z o mancuernas. Flexiona los codos sin despegar los brazos del soporte y baja lentamente sin bloquearlos; evita rebotar abajo, elevar los hombros o levantar el torso.', 'Adjust the preacher bench so the backs of your upper arms are fully supported and hold an EZ bar or dumbbells. Curl without lifting your arms from the pad and lower slowly without locking out, bouncing at the bottom, shrugging, or raising your torso.'),
    ('Curl Martillo', 'Sostén las mancuernas con palmas enfrentadas y codos junto al cuerpo. Flexiona los codos manteniendo el agarre neutro, pausa arriba y baja con control para trabajar bíceps, braquial y braquiorradial; evita balancearte o adelantar los codos.', 'Hold dumbbells with palms facing each other and elbows beside your body. Curl while maintaining the neutral grip, pause at the top, and lower under control to train the biceps, brachialis, and brachioradialis without swinging or moving your elbows forward.'),
    ('Curl Martillo con Mancuernas', 'De pie o sentado, mantén las mancuernas en agarre neutro y los hombros relajados. Lleva las cargas hacia los hombros flexionando solo los codos y baja lentamente; evita usar la cadera, doblar las muñecas o transformar el movimiento en una elevación frontal.', 'Stand or sit with dumbbells in a neutral grip and relaxed shoulders. Bring the weights toward your shoulders by bending only your elbows and lower slowly, avoiding hip drive, wrist bending, or turning the movement into a front raise.'),
    ('Curl Martillo en Polea con Cuerda', 'Frente a la polea baja, toma los extremos de la cuerda con agarre neutro y postura firme. Flexiona los codos manteniéndolos junto al torso, separa levemente la cuerda arriba y vuelve controlando; evita inclinarte, encoger los hombros o mover los codos.', 'Face a low cable, hold the rope ends with a neutral grip, and take a stable stance. Curl with your elbows beside your torso, separate the rope slightly at the top, and return under control without leaning, shrugging, or moving your elbows.'),
    ('Dominadas', 'Cuélgate de la barra con agarre cómodo y hombros activos. Inicia descendiendo las escápulas, lleva el pecho hacia la barra flexionando los codos y baja hasta extender con control; evita balancearte, sacar la cabeza hacia adelante o recortar el recorrido.', 'Hang from the bar with a comfortable grip and active shoulders. Initiate by drawing your shoulder blades down, pull your chest toward the bar, and lower to controlled extension without swinging, craning your head forward, or shortening the range.'),
    ('Dominadas (Pull-ups)', 'Toma la barra con agarre pronado algo más ancho que los hombros y estabiliza el tronco. Desciende las escápulas, tira llevando los codos hacia abajo hasta acercar el pecho a la barra y baja lentamente; evita impulso de piernas o relajarte bruscamente abajo.', 'Grip the bar overhand slightly wider than shoulder width and stabilize your torso. Depress your shoulder blades, pull your elbows downward until your chest nears the bar, and lower slowly without leg momentum or suddenly relaxing at the bottom.'),
    ('Dorsalera', 'Ajusta el asiento y el apoyo de muslos, toma la barra con un agarre cómodo y siéntate erguido. Lleva los codos hacia abajo y atrás para acercar la barra al pecho, luego extiende lentamente; evita tirar detrás del cuello, balancear el torso o usar impulso.', 'Adjust the seat and thigh pad, take a comfortable grip, and sit tall. Drive your elbows down and back to bring the bar toward your chest, then extend slowly without pulling behind your neck, rocking your torso, or using momentum.'),
    ('Jalón al Pecho', 'Sujeta la barra de la polea alta, fija los muslos y mantén una ligera inclinación estable del torso. Baja la barra hacia la parte alta del pecho llevando los codos al costado y regresa lentamente; evita tirar detrás de la cabeza, encoger los hombros o balancearte.', 'Grip the high-cable bar, secure your thighs, and keep a slight stable torso lean. Pull the bar toward your upper chest by driving your elbows down, then return slowly without pulling behind your head, shrugging, or rocking.'),
    ('Pullover con Mancuerna', 'Acostado en un banco, sostén una mancuerna sobre el pecho con ambas manos y codos suavemente flexionados. Llévala en arco detrás de la cabeza hasta un estiramiento cómodo y vuelve usando los dorsales; evita abrir los codos, arquear la espalda o bajar más allá de tu movilidad.', 'Lie on a bench holding one dumbbell above your chest with both hands and softly bent elbows. Lower it in an arc behind your head to a comfortable stretch and return using your lats, avoiding flared elbows, back arching, or excessive depth.'),
    ('Pullover en Máquina', 'Ajusta asiento y apoyo para alinear los hombros con el eje de la máquina y fija el torso. Empuja el brazo o almohadilla en arco hacia abajo usando los dorsales y regresa lentamente al estiramiento; evita despegar la espalda o convertirlo en un movimiento de tríceps.', 'Adjust the seat and pad so your shoulders align with the machine axis and keep your torso supported. Drive the lever downward in an arc using your lats and return slowly to the stretch without lifting your back or turning it into a triceps movement.'),
    ('Pullover en Polea Alta', 'Frente a la polea alta, toma una barra o cuerda, inclina ligeramente el torso y mantén los brazos casi extendidos. Lleva el accesorio hacia los muslos mediante la extensión de hombros y vuelve controlando; evita doblar mucho los codos o arquear la zona lumbar.', 'Face a high cable, hold a bar or rope, lean forward slightly, and keep your arms nearly straight. Pull the attachment toward your thighs through shoulder extension and return under control without excessive elbow bending or lower-back arching.'),
    ('Remo con Barra', 'Inclina el torso desde la cadera con espalda neutra, rodillas suaves y abdomen firme. Tira de la barra hacia el abdomen llevando los codos atrás, junta las escápulas y baja hasta extender; evita redondear la espalda, levantarte en cada repetición o usar rebote.', 'Hinge at the hips with a neutral back, soft knees, and a braced core. Row the bar toward your abdomen by driving your elbows back, squeeze your shoulder blades, and lower to extension without rounding, standing up each rep, or bouncing.'),
    ('Remo con Barra T y Pecho Apoyado', 'Ajusta el soporte para mantener el pecho firme y toma las manijas con agarre cómodo. Lleva los codos hacia atrás y rema la barra T hacia el torso, pausa sin encoger los hombros y baja lentamente hasta extender los brazos.', 'Adjust the support so your chest stays firmly planted and take a comfortable grip. Drive your elbows back to row the T-bar toward your torso, pause without shrugging, and lower slowly until your arms extend.'),
    ('Remo con Mancuernas y Pecho Apoyado', 'Acuéstate boca abajo en un banco inclinado con el pecho completamente apoyado y mancuernas colgando. Rema hacia los costados del torso, junta las escápulas y baja controlando; evita despegar el pecho, elevar los hombros o lanzar las cargas.', 'Lie face down on an incline bench with your chest fully supported and dumbbells hanging. Row toward the sides of your torso, squeeze your shoulder blades, and lower under control without lifting your chest, shrugging, or throwing the weights.'),
    ('Remo en Máquina con Pecho Apoyado', 'Ajusta asiento y apoyo para que el pecho permanezca firme y las manijas queden a una altura cómoda. Tira llevando los codos atrás, pausa con las escápulas juntas y vuelve lentamente; evita encoger los hombros o separar el torso del respaldo.', 'Adjust the seat and pad so your chest stays firm and the handles sit at a comfortable height. Pull by driving your elbows back, pause with your shoulder blades together, and return slowly without shrugging or lifting your torso from the pad.'),
    ('Remo Gironda', 'Adopta una posición estable frente al implemento y mantén el torso erguido o levemente inclinado según la variante. Lleva el agarre hacia la zona media del abdomen, junta las escápulas y vuelve extendiendo con control; evita balancearte o elevar los hombros.', 'Take a stable position at the implement and keep your torso upright or slightly inclined according to the variation. Pull the handle toward your mid-abdomen, squeeze your shoulder blades, and return to extension under control without rocking or shrugging.'),
    ('Remo Gironda (Polea Baja)', 'Siéntate frente a la polea baja con pies apoyados, rodillas suaves y espalda neutra. Tira del agarre estrecho hacia el abdomen llevando los codos atrás, pausa y extiende lentamente sin redondear la zona lumbar ni balancear el torso.', 'Sit at the low cable with supported feet, soft knees, and a neutral back. Pull the close handle toward your abdomen by driving your elbows back, pause, and extend slowly without rounding your lower back or rocking your torso.'),
    ('Remo Pendlay en Máquina', 'Ajusta la máquina para iniciar con brazos extendidos y torso estable, con o sin apoyo según el diseño. Rema de forma firme hacia la parte baja del pecho, detén el movimiento con las escápulas y regresa controlando; evita impulso lumbar o encoger los hombros.', 'Adjust the machine to begin with extended arms and a stable torso, using the support provided by its design. Row firmly toward your lower chest, finish with your shoulder blades, and return under control without lower-back momentum or shrugging.'),
    ('Encogimientos (Shrugs)', 'De pie, sostén mancuernas o barra con brazos extendidos y postura erguida. Eleva los hombros directamente hacia las orejas, pausa contrayendo el trapecio y baja lentamente; evita hacer círculos, flexionar los codos o adelantar la cabeza.', 'Stand tall holding dumbbells or a bar with straight arms. Raise your shoulders directly toward your ears, pause to squeeze your traps, and lower slowly without rolling your shoulders, bending your elbows, or pushing your head forward.'),
    ('Remo al Mentón', 'De pie, toma una barra o cable con agarre cómodo y muñecas neutras. Eleva el implemento cerca del cuerpo guiando con los codos hasta una altura que no cause molestia y baja lentamente; evita un agarre demasiado estrecho, elevar de más o encoger los hombros.', 'Stand with a comfortable grip on a bar or cable and neutral wrists. Raise the implement close to your body by leading with your elbows to a pain-free height, then lower slowly without using an overly narrow grip, pulling too high, or shrugging.')
)
update public.exercises as exercise
set
  description = descriptions.description_es,
  description_en = descriptions.description_en
from descriptions
where exercise.user_id is null
  and lower(exercise.name) = lower(descriptions.name_es);
