with descriptions (name_es, description_es, description_en) as (
  values
    ('Abducción en Polea o Banda', 'Coloca la polea baja o la banda en el tobillo más alejado del anclaje y sostente para mantener el equilibrio. Con el tronco estable y la pelvis nivelada, separa la pierna hacia un lado sin girar la cadera. Regresa lentamente hasta la posición inicial y evita impulsarte o inclinar el cuerpo.', 'Attach a low cable or band to the ankle farthest from the anchor and hold a support for balance. Keep your torso steady and hips level as you move the leg out to the side without rotating the pelvis. Return slowly to the starting position, avoiding momentum or leaning away.'),
    ('Apertura en Máquina Abductora', 'Siéntate con la espalda apoyada y coloca la parte externa de las piernas contra las almohadillas. Abre las rodillas empujando desde las caderas hasta un rango cómodo, sin despegar la pelvis del asiento. Haz una breve pausa y vuelve de forma controlada, evitando que el peso cierre las piernas de golpe.', 'Sit with your back supported and place the outside of your legs against the pads. Drive your knees apart from the hips through a comfortable range without lifting your pelvis from the seat. Pause briefly, then return under control instead of letting the weight pull your legs together.'),
    ('Aductor en Máquina', 'Siéntate con la espalda apoyada y la cara interna de las piernas contra las almohadillas. Parte con las rodillas abiertas en un rango cómodo y júntalas apretando los aductores, sin levantar la pelvis ni cerrar con impulso. Mantén una breve contracción y vuelve lentamente hasta sentir un estiramiento controlado.', 'Sit with your back supported and the inside of your legs against the pads. Begin with your knees apart in a comfortable range and bring them together by squeezing the inner thighs without lifting your pelvis or using momentum. Pause briefly, then return slowly to a controlled stretch.'),
    ('Aductores en Máquina', 'Ajusta el asiento y las almohadillas para comenzar con una apertura cómoda de cadera. Mantén la espalda apoyada y acerca las piernas entre sí apretando la cara interna de los muslos. Evita rebotar, despegar la pelvis o soltar el peso al regresar; controla tanto el cierre como la apertura.', 'Adjust the seat and pads so your hips begin in a comfortable open position. Keep your back supported and bring your legs together by contracting the inner thighs. Avoid bouncing, lifting your pelvis, or releasing the weight on the return; control both the closing and opening phases.'),
    ('Cierre en Máquina Aductora', 'Siéntate firme, apoya la espalda y coloca la cara interna de las piernas sobre las almohadillas. Desde una apertura tolerable, cierra las rodillas de manera uniforme hasta juntar las piernas sin forzar la cadera. Pausa un instante y abre lentamente, manteniendo la pelvis estable durante todo el recorrido.', 'Sit firmly with your back supported and the inside of your legs against the pads. From a comfortable open position, bring your knees together evenly without forcing the hips. Pause for a moment, then open slowly while keeping your pelvis stable throughout the movement.'),
    ('Estocadas', 'De pie, da un paso suficientemente largo y desciende ambas rodillas manteniendo el torso erguido y el pie delantero completamente apoyado. La rodilla delantera debe seguir la dirección de los dedos del pie. Empuja el suelo para volver y evita perder el equilibrio, juntar demasiado los pies o golpear la rodilla trasera.', 'Stand tall, take a sufficiently long step, and lower both knees while keeping your torso upright and the front foot fully planted. Let the front knee track in the same direction as the toes. Push through the floor to return, avoiding a narrow stance, loss of balance, or striking the rear knee.'),
    ('Extensión de Cuádriceps', 'Ajusta el respaldo y el rodillo para que la rodilla coincida con el eje de la máquina y la almohadilla quede sobre la parte baja de la tibia. Extiende las piernas sin levantar la pelvis ni bloquear las rodillas con violencia. Contrae arriba y baja lentamente hasta recuperar la flexión inicial.', 'Adjust the backrest and roller so your knee aligns with the machine axis and the pad rests over the lower shin. Extend your legs without lifting your pelvis or forcefully locking the knees. Contract at the top, then lower slowly until you return to the starting knee bend.'),
    ('Prensa (Leg Press)', 'Apoya toda la espalda y la pelvis contra el respaldo, con los pies firmes sobre la plataforma al ancho adecuado. Desbloquea el seguro y flexiona rodillas y caderas hasta donde puedas mantener la zona lumbar apoyada. Empuja la plataforma sin juntar las rodillas ni bloquearlas bruscamente al extender.', 'Keep your entire back and pelvis against the pad, with both feet firmly placed on the platform at a comfortable width. Release the safety and bend your knees and hips only as far as you can keep your lower back supported. Press without letting the knees cave in or snapping them into lockout.'),
    ('Prensa de Piernas (Leg Press)', 'Coloca los pies estables en la plataforma y mantén espalda, cabeza y pelvis apoyadas. Baja la carga flexionando caderas y rodillas con estas alineadas sobre los pies, sin redondear la zona lumbar. Empuja de manera uniforme con ambos pies y termina la extensión sin bloquear las rodillas de golpe.', 'Place both feet securely on the platform and keep your back, head, and pelvis supported. Lower the load by bending your hips and knees while tracking the knees over the feet, without rounding your lower back. Press evenly through both feet and finish without forcefully locking the knees.'),
    ('Sentadilla Búlgara', 'Apoya el empeine trasero en un banco y coloca el pie delantero lo bastante lejos para descender con estabilidad. Baja la rodilla trasera mientras la rodilla delantera sigue la línea del pie y el tronco permanece firme. Empuja con la pierna delantera para subir, evitando impulsarte con el pie elevado.', 'Rest the rear instep on a bench and place the front foot far enough forward to descend with balance. Lower the rear knee while the front knee tracks over the foot and your torso stays braced. Drive through the front leg to rise, avoiding assistance or momentum from the elevated foot.'),
    ('Sentadilla Libre', 'Coloca los pies en una postura estable y mantén el abdomen firme. Lleva las caderas hacia abajo mientras flexionas las rodillas en la dirección de los pies, conservando el apoyo completo del talón y el mediopié. Sube empujando el suelo, sin dejar que las rodillas colapsen hacia dentro ni perder la posición del tronco.', 'Set your feet in a stable stance and brace your trunk. Lower your hips as your knees bend in the direction of your toes, keeping the heel and midfoot firmly planted. Stand by driving through the floor without allowing the knees to cave inward or losing your torso position.'),
    ('Sentadillas', 'Adopta una postura cómoda con los pies firmes y el tronco activo. Flexiona caderas y rodillas para descender, manteniendo las rodillas alineadas con los pies y el peso distribuido sobre toda la planta. Regresa extendiendo caderas y rodillas a la vez, sin rebotar abajo ni redondear la espalda.', 'Take a comfortable stance with your feet planted and torso braced. Bend your hips and knees to descend while keeping the knees aligned with the feet and pressure across the whole foot. Return by extending the hips and knees together, without bouncing at the bottom or rounding your back.'),
    ('Sillón Cuádriceps (Leg Extension)', 'Alinea las rodillas con el pivote de la máquina, apoya bien la espalda y coloca el rodillo sobre la parte baja de las tibias. Eleva la carga extendiendo las rodillas con control, sin despegar la cadera del asiento. Aprieta los cuádriceps arriba y desciende lentamente, sin dejar caer el peso.', 'Align your knees with the machine pivot, support your back, and place the roller over the lower shins. Lift the load by extending your knees under control without raising your hips from the seat. Squeeze the quadriceps at the top and lower slowly instead of dropping the weight.'),
    ('Zancadas (Lunges)', 'Desde una posición erguida, avanza o retrocede con un paso estable y baja ambas rodillas de forma controlada. Mantén el pie delantero apoyado, la rodilla alineada con sus dedos y la pelvis orientada al frente. Impúlsate con la pierna de trabajo para volver, sin balancear el tronco.', 'From a tall stance, step forward or backward into a stable split position and lower both knees under control. Keep the front foot planted, the knee aligned with its toes, and the pelvis facing forward. Drive through the working leg to return without swinging your torso.'),
    ('Hip Thrust (Empuje de Cadera)', 'Apoya la parte alta de la espalda en un banco y coloca los pies firmes, de modo que las tibias queden cerca de verticales al subir. Eleva la cadera contrayendo los glúteos hasta alinear hombros, caderas y rodillas. Evita arquear la zona lumbar o empujar con el cuello y baja con control.', 'Support your upper back on a bench and plant your feet so the shins are close to vertical at the top. Drive your hips upward by squeezing the glutes until shoulders, hips, and knees align. Avoid overextending the lower back or pushing through the neck, and lower under control.'),
    ('Patada Trasera en Polea', 'Sujeta una polea baja al tobillo y estabiliza el tronco con una ligera inclinación hacia delante. Lleva la pierna hacia atrás desde la cadera, con la pelvis nivelada y la rodilla apenas flexionada. Contrae el glúteo sin arquear la espalda ni girar el cuerpo y vuelve lentamente.', 'Attach a low cable to your ankle and stabilize your torso with a slight forward lean. Move the leg backward from the hip while keeping the pelvis level and the knee slightly bent. Squeeze the glute without arching your back or rotating your body, then return slowly.'),
    ('Posteriores en Máquina', 'Ajusta la máquina para que el apoyo permita extender la cadera sin forzar la espalda. Mantén el tronco firme y empuja la plataforma o almohadilla hacia atrás contrayendo el glúteo, sin girar la pelvis. Completa un rango controlado y regresa despacio, evitando tomar impulso con el cuerpo.', 'Adjust the machine so the support allows hip extension without straining your back. Brace your torso and drive the platform or pad backward by contracting the glute without rotating the pelvis. Use a controlled range and return slowly, avoiding momentum from the rest of the body.'),
    ('Puente Glúteo Básico', 'Acuéstate boca arriba con las rodillas flexionadas y los pies apoyados cerca de los glúteos. Presiona el suelo y eleva la pelvis hasta formar una línea entre hombros, caderas y rodillas. Aprieta los glúteos arriba sin hiperextender la zona lumbar y desciende de forma controlada.', 'Lie on your back with knees bent and feet planted near the glutes. Press into the floor and lift your pelvis until shoulders, hips, and knees form a line. Squeeze the glutes at the top without overextending the lower back, then lower under control.'),
    ('Sentadilla Sumo', 'Separa los pies más que el ancho de hombros y orienta las puntas ligeramente hacia fuera. Desciende llevando caderas y rodillas en la dirección de los pies, con el tronco firme y toda la planta apoyada. Empuja el suelo para subir, evitando que las rodillas caigan hacia dentro o que la espalda se redondee.', 'Set your feet wider than shoulder width with the toes turned slightly outward. Lower your hips while the knees track in the direction of the feet, keeping your torso braced and the whole foot planted. Drive through the floor to rise without letting the knees cave inward or rounding your back.'),
    ('Camilla Isquiotibiales (Hamstring Curl)', 'Ajusta el eje de la máquina a la altura de las rodillas y coloca el rodillo sobre la parte baja de las piernas. Mantén la pelvis apoyada y flexiona las rodillas acercando los talones a los glúteos. Contrae los isquiotibiales y vuelve lentamente, sin levantar la cadera ni soltar el peso.', 'Align the machine pivot with your knees and position the roller over the lower legs. Keep your pelvis supported as you bend the knees and bring the heels toward the glutes. Contract the hamstrings, then return slowly without lifting the hips or releasing the weight.'),
    ('Curl de Piernas Sentado', 'Ajusta el respaldo, el apoyo sobre los muslos y el rodillo para alinear las rodillas con el eje de la máquina. Flexiona las rodillas llevando los talones hacia abajo y atrás, sin despegar la pelvis. Pausa en la contracción y extiende lentamente hasta el rango inicial, manteniendo tensión.', 'Adjust the backrest, thigh restraint, and roller so your knees align with the machine pivot. Bend the knees by drawing the heels down and back without lifting your pelvis. Pause at the contraction, then extend slowly to the starting range while maintaining tension.'),
    ('Curl de Piernas Tumbado', 'Acuéstate con las rodillas alineadas con el pivote y el rodillo apoyado por encima de los talones. Mantén caderas y abdomen contra el banco mientras flexionas las rodillas. Acerca los talones sin arquear la espalda ni levantar la pelvis, y baja la carga de forma lenta y controlada.', 'Lie face down with your knees aligned to the pivot and the roller resting just above the heels. Keep your hips and abdomen against the bench as you bend the knees. Bring the heels in without arching your back or lifting the pelvis, then lower the load slowly and under control.'),
    ('Peso Muerto Rumano', 'Sostén la carga cerca de los muslos, flexiona levemente las rodillas y lleva la cadera hacia atrás manteniendo la espalda neutra. Desciende hasta sentir tensión en los isquiotibiales sin alejar el peso del cuerpo. Empuja las caderas hacia delante para subir, evitando convertir el movimiento en una sentadilla.', 'Hold the load close to your thighs, soften the knees, and push your hips backward while maintaining a neutral spine. Lower until you feel tension in the hamstrings without letting the weight drift away. Drive the hips forward to stand, avoiding turning the movement into a squat.'),
    ('Sillón Isquiotibiales (Leg Curl)', 'Siéntate con la espalda y los muslos bien sujetos, alinea las rodillas con el eje y coloca el rodillo sobre la parte baja de las piernas. Flexiona las rodillas llevando los talones hacia atrás sin levantar la cadera. Aprieta al final y vuelve despacio, controlando la extensión completa.', 'Sit with your back and thighs securely supported, align your knees with the pivot, and place the roller over the lower legs. Bend the knees by drawing the heels backward without lifting the hips. Squeeze at the end and return slowly, controlling the full extension.'),
    ('Hiperextensiones', 'Ajusta el banco para que el apoyo quede debajo de la cadera y fija los pies. Con el tronco firme, inclínate desde la cadera manteniendo la espalda neutra y baja hasta un rango cómodo. Extiende la cadera para volver hasta alinear el cuerpo, sin hiperextender ni lanzar el torso.', 'Adjust the bench so the pad sits below your hips and secure your feet. With your trunk braced, hinge from the hips while maintaining a neutral spine and lower through a comfortable range. Extend the hips to return until your body is aligned, without overextending or swinging the torso.'),
    ('Supermans', 'Acuéstate boca abajo con brazos y piernas extendidos y el cuello alineado. Eleva ligeramente brazos, pecho y piernas contrayendo glúteos y musculatura posterior, sin buscar una altura excesiva. Mantén un instante, respira y baja con control, evitando comprimir la zona lumbar.', 'Lie face down with arms and legs extended and your neck aligned. Gently raise the arms, chest, and legs by engaging the glutes and posterior muscles without chasing excessive height. Hold briefly, breathe, and lower under control while avoiding compression in the lower back.'),
    ('Elevación de Talones de Pie', 'De pie sobre una base estable, apoya el antepié y deja que los talones desciendan hasta un estiramiento cómodo. Eleva los talones empujando a través de los dedos y manteniendo tobillos, rodillas y caderas alineados. Pausa arriba y baja lentamente, sin rebotar ni girar los pies.', 'Stand on a stable surface with the balls of your feet supported and lower the heels to a comfortable stretch. Raise the heels by pressing through the forefoot while keeping ankles, knees, and hips aligned. Pause at the top and lower slowly without bouncing or rolling the feet.'),
    ('Elevación de Talones Sentado', 'Siéntate con los pies apoyados sobre el antepié y la carga estable sobre los muslos, cerca de las rodillas. Baja los talones de forma controlada y luego elévalos todo lo posible contrayendo las pantorrillas. Mantén una pausa arriba y evita rebotar o perder el apoyo del antepié.', 'Sit with the balls of your feet supported and the load secured over the thighs near the knees. Lower the heels under control, then raise them as high as possible by contracting the calves. Pause at the top and avoid bouncing or losing contact through the forefoot.'),
    ('Extensión de Gemelos', 'Coloca el antepié sobre una superficie firme y estabiliza el cuerpo. Permite que los talones bajen hasta un estiramiento cómodo y luego extiende los tobillos para elevarlos, distribuyendo la presión de manera uniforme. Contrae arriba y regresa lentamente, sin impulsos ni balanceos.', 'Place the balls of your feet on a firm surface and stabilize your body. Let the heels lower to a comfortable stretch, then extend the ankles to raise them while distributing pressure evenly across the forefoot. Contract at the top and return slowly without momentum or swaying.')
)
update public.exercises as exercise
set description = descriptions.description_es,
    description_en = descriptions.description_en
from descriptions
where exercise.user_id is null
  and lower(exercise.name) = lower(descriptions.name_es);
