with descriptions (name_es, description_es, description_en) as (
  values
    ('Deltoides Posteriores en Máquina', 'Ajusta el asiento para que las manijas queden a la altura de los hombros y apoya el pecho contra el respaldo. Con codos suavemente flexionados, abre los brazos en arco hasta alinear con el torso, junta las escápulas sin encoger los hombros y vuelve lentamente.', 'Adjust the seat so the handles are level with your shoulders and keep your chest against the pad. With softly bent elbows, open your arms in an arc until they align with your torso, squeeze your shoulder blades without shrugging, and return slowly.'),
    ('Elevaciones Laterales', 'De pie o sentado, sostén las mancuernas a los lados con codos ligeramente flexionados. Eleva los brazos en el plano de las escápulas hasta cerca de la altura de los hombros y baja con control; evita balancearte, encoger los hombros o subir las manos muy por encima de los codos.', 'Stand or sit holding dumbbells at your sides with slightly bent elbows. Raise your arms in the scapular plane to about shoulder height and lower under control, avoiding body swing, shoulder shrugging, or lifting your hands far above your elbows.'),
    ('Face Pull con Polea', 'Coloca una cuerda en la polea alta y retrocede con el torso erguido. Tira hacia la frente separando los extremos y llevando codos altos, rota externamente los hombros al final y vuelve controlando; evita arquear la espalda o encoger el cuello.', 'Attach a rope to a high cable and step back with an upright torso. Pull toward your forehead while separating the rope and keeping your elbows high, externally rotate at the finish, and return under control without arching your back or shrugging.'),
    ('Pájaros (Reverse Flyes)', 'Inclina el torso con espalda neutra o apoya el pecho en un banco inclinado. Con mancuernas y codos suavemente flexionados, abre los brazos hacia los lados hasta alinear con el torso, pausa y baja lentamente; evita usar impulso o acercar los hombros a las orejas.', 'Hinge forward with a neutral back or support your chest on an incline bench. With dumbbells and softly bent elbows, open your arms until they align with your torso, pause, and lower slowly without using momentum or shrugging.'),
    ('Press Arnold', 'Sentado con respaldo, comienza con mancuernas frente a los hombros y palmas hacia ti. Abre y rota los brazos mientras presionas por encima de la cabeza, termina con palmas al frente y vuelve por el mismo recorrido; evita arquear la zona lumbar o forzar la rotación.', 'Sit against a backrest with dumbbells in front of your shoulders and palms facing you. Open and rotate your arms as you press overhead, finish with palms forward, and reverse the path without arching your lower back or forcing the rotation.'),
    ('Press Militar', 'De pie o sentado, toma la barra algo más ancho que los hombros y colócala sobre la parte alta del pecho. Contrae abdomen y glúteos, presiona en línea vertical hasta extender los brazos y baja con control; evita inclinarte hacia atrás o abrir excesivamente los codos.', 'Stand or sit with a grip slightly wider than shoulder width and hold the bar on your upper chest. Brace your core and glutes, press vertically until your arms extend, and lower under control without leaning backward or flaring your elbows excessively.'),
    ('Press Militar con Mancuernas', 'De pie o sentado, coloca las mancuernas a la altura de los hombros con muñecas neutras. Presiona hacia arriba y ligeramente hacia dentro hasta extender los brazos, luego baja lentamente; mantén costillas y pelvis alineadas y evita golpear las mancuernas o arquear la espalda.', 'Stand or sit with dumbbells at shoulder height and neutral wrists. Press upward and slightly inward until your arms extend, then lower slowly while keeping ribs and pelvis aligned and avoiding clashing the dumbbells or arching your back.'),
    ('Vuelos Laterales', 'Sostén una mancuerna en cada mano y mantén una ligera flexión de codos. Eleva los brazos lateralmente en un recorrido controlado hasta la altura de los hombros y desciende sin perder tensión; usa una carga que evite balanceos, impulso de piernas o elevación excesiva de los hombros.', 'Hold a dumbbell in each hand with a slight bend in your elbows. Raise your arms laterally under control to shoulder height and lower without losing tension, using a load that prevents body swing, leg drive, or excessive shoulder elevation.'),
    ('Aperturas con Mancuernas', 'Acostado en banco plano o inclinado, sostén las mancuernas sobre el pecho con palmas enfrentadas y codos levemente flexionados. Abre los brazos en arco hasta sentir un estiramiento cómodo, mantén las escápulas estables y vuelve como si abrazaras; evita bajar más allá de tu movilidad.', 'Lie on a flat or incline bench with dumbbells above your chest, palms facing, and elbows slightly bent. Open your arms in an arc to a comfortable stretch, keep your shoulder blades stable, and return as if hugging without lowering beyond your available mobility.'),
    ('Cruces en PoleaAlta', 'Colócate entre dos poleas altas con un pie adelantado y el torso ligeramente inclinado. Lleva los agarres hacia abajo y al centro mediante un arco amplio, junta las manos frente al cuerpo y vuelve lentamente; evita flexionar y extender los codos durante el recorrido o perder la postura.', 'Stand between two high cables with a staggered stance and a slight forward lean. Bring the handles down and inward through a wide arc, meet your hands in front of your body, and return slowly without repeatedly bending your elbows or losing posture.'),
    ('Flexiones de Pecho (Push-ups)', 'Coloca manos algo más anchas que los hombros y alinea cabeza, tronco y piernas. Baja el cuerpo como una unidad hasta acercar el pecho al suelo, mantén codos en un ángulo cómodo y empuja separando el piso; evita hundir la cintura, adelantar la cabeza o abrir los codos por completo.', 'Place your hands slightly wider than shoulder width and align your head, torso, and legs. Lower your body as one unit until your chest nears the floor, keep your elbows at a comfortable angle, and push the floor away without sagging, craning your neck, or fully flaring your elbows.'),
    ('Mariposa (Pec Deck)', 'Ajusta el asiento para que codos o manijas queden a la altura media del pecho y apoya toda la espalda. Junta los brazos frente al cuerpo manteniendo una flexión estable de codos, contrae el pecho y regresa lentamente hasta un estiramiento cómodo; evita despegar los hombros del respaldo.', 'Adjust the seat so the pads or handles are level with your mid-chest and keep your back supported. Bring your arms together with a stable elbow bend, squeeze your chest, and return slowly to a comfortable stretch without lifting your shoulders from the pad.'),
    ('Press de Banca Inclinado', 'Ajusta el banco entre 30 y 45 grados, fija los pies y retrae suavemente las escápulas. Baja la carga hacia la parte alta del pecho con antebrazos verticales y presiona sin perder el apoyo; evita rebotar, elevar los hombros o exagerar el arco lumbar.', 'Set the bench between 30 and 45 degrees, plant your feet, and gently retract your shoulder blades. Lower the load toward your upper chest with vertical forearms and press without losing support, avoiding bouncing, shrugged shoulders, or an exaggerated lower-back arch.'),
    ('Press de Banca Plano', 'Acostado en banco plano, fija pies, glúteos y parte alta de la espalda y toma la barra algo más ancho que los hombros. Baja hacia la zona media del pecho con control y presiona hasta extender los brazos; evita rebotar la barra, despegar la cadera o perder la posición de las muñecas.', 'Lie on a flat bench with your feet, glutes, and upper back firmly set and grip the bar slightly wider than shoulder width. Lower it to your mid-chest under control and press to arm extension without bouncing, lifting your hips, or losing wrist alignment.'),
    ('Press Inclinado con Mancuernas', 'En un banco inclinado entre 30 y 45 grados, apoya pies y espalda y coloca las mancuernas junto a la parte alta del pecho. Presiona hacia arriba y ligeramente hacia dentro, luego baja con codos controlados; evita chocar las mancuernas, arquear demasiado la espalda o perder estabilidad.', 'On a bench inclined between 30 and 45 degrees, support your feet and back and hold the dumbbells beside your upper chest. Press upward and slightly inward, then lower with controlled elbows without clashing the weights, overarching your back, or losing stability.'),
    ('Press Plano con Barra', 'Acuéstate en banco plano, planta los pies y estabiliza las escápulas contra el banco. Toma la barra con agarre medio, bájala hacia el pecho manteniendo muñecas sobre codos y empuja en un recorrido estable; evita rebotar, levantar la pelvis o bloquear los codos de forma brusca.', 'Lie on a flat bench, plant your feet, and stabilize your shoulder blades against the pad. Use a medium grip, lower the bar toward your chest with wrists stacked over elbows, and press along a steady path without bouncing, lifting your hips, or snapping your elbows.'),
    ('Extensión de Tríceps en Polea con Cuerda', 'Frente a la polea alta, toma la cuerda con agarre neutro y fija los codos junto al torso. Extiende los antebrazos hacia abajo, separa ligeramente los extremos al final y vuelve hasta cerca de 90 grados; evita mover hombros, inclinarte sobre la carga o abrir los codos.', 'Face a high cable, hold the rope with a neutral grip, and pin your elbows beside your torso. Extend your forearms downward, separate the rope slightly at the bottom, and return to about 90 degrees without moving your shoulders, leaning onto the load, or flaring your elbows.'),
    ('Extensión de Tríceps por Encima de la Cabeza con Cable', 'De espaldas a una polea baja o media, lleva la cuerda por encima de la cabeza y adelanta un pie. Mantén codos apuntando al frente, extiende los brazos sin mover los hombros y vuelve lentamente hasta sentir estiramiento; evita arquear la espalda o separar demasiado los codos.', 'Face away from a low or mid cable, bring the rope overhead, and take a staggered stance. Keep your elbows pointing forward, extend your arms without moving your shoulders, and return slowly to a stretch without arching your back or letting your elbows spread.'),
    ('Extensión de Tríceps por Encima de la Cabeza con Mancuerna', 'De pie o sentado, sostén una mancuerna con ambas manos sobre la cabeza y mantén el abdomen firme. Flexiona solo los codos para bajar la carga detrás de la cabeza y extiéndelos de nuevo; evita abrir los codos, adelantar la cabeza o arquear la zona lumbar.', 'Stand or sit holding one dumbbell overhead with both hands and brace your core. Bend only your elbows to lower the weight behind your head, then extend them again without flaring your elbows, pushing your head forward, or arching your lower back.'),
    ('Extensión de Tríceps Unilateral en Polea', 'Colócate frente a la polea alta y toma una manija con una mano. Mantén el brazo superior junto al torso, extiende el codo hasta contraer el tríceps y regresa lentamente; evita rotar el cuerpo, elevar el hombro o acompañar el movimiento con el brazo completo.', 'Stand facing a high cable and hold a single handle. Keep your upper arm beside your torso, extend your elbow to contract the triceps, and return slowly without rotating your body, shrugging, or moving the entire arm.'),
    ('Extensión en Polea Alta', 'Frente a la polea alta, toma una barra recta, en V o una cuerda y adopta una postura estable. Mantén codos pegados al cuerpo, extiende los antebrazos hasta abajo y vuelve controlando; evita inclinarte en exceso, usar el peso corporal o dejar que los codos avancen.', 'Face a high cable with a straight bar, V-bar, or rope and take a stable stance. Keep your elbows close, extend your forearms fully downward, and return under control without excessive leaning, using body weight, or allowing your elbows to drift forward.'),
    ('Extensión Unilateral de Tríceps por Encima de la Cabeza', 'De pie o sentado, eleva una mancuerna con un brazo y estabiliza hombro y tronco. Flexiona el codo para bajar la carga detrás de la cabeza y extiende hasta arriba manteniendo el brazo superior quieto; evita inclinarte, abrir el codo o forzar el cuello.', 'Stand or sit with one dumbbell overhead and stabilize your shoulder and torso. Bend your elbow to lower the weight behind your head and extend it while keeping your upper arm still, avoiding side bending, elbow flaring, or neck strain.'),
    ('Fondos en Banco', 'Apoya las manos en el borde de un banco junto a las caderas y coloca los pies al frente. Desplaza el cuerpo cerca del banco, flexiona los codos hasta un rango cómodo y empuja para volver; evita bajar demasiado, adelantar los hombros o separar el torso del apoyo.', 'Place your hands on the edge of a bench beside your hips and position your feet forward. Keep your body close to the bench, bend your elbows through a comfortable range, and press back up without descending too far, rolling your shoulders forward, or drifting away from the bench.'),
    ('Fondos en Paralelas (Dips)', 'Sujeta las barras con hombros deprimidos y brazos extendidos. Baja flexionando los codos hasta un rango cómodo, mantén el torso relativamente erguido para enfatizar tríceps y empuja hasta arriba; evita rebotar, encoger los hombros o forzar profundidad sin movilidad.', 'Support yourself on parallel bars with depressed shoulders and straight arms. Lower through a comfortable elbow bend, keep your torso relatively upright to emphasize the triceps, and press back up without bouncing, shrugging, or forcing depth beyond your mobility.'),
    ('Patada de Tríceps', 'Inclina el torso con espalda neutra y lleva el brazo superior junto al cuerpo, paralelo al suelo. Extiende el codo hasta alinear el antebrazo, pausa contrayendo el tríceps y vuelve lentamente; evita balancear la mancuerna, mover el hombro o girar el tronco.', 'Hinge forward with a neutral back and hold your upper arm beside your body, parallel to the floor. Extend your elbow until the forearm aligns, pause to squeeze the triceps, and return slowly without swinging the dumbbell, moving your shoulder, or rotating your torso.'),
    ('Press de Banca con Agarre Cerrado', 'Acuéstate en banco plano, fija pies y escápulas y toma la barra aproximadamente al ancho de hombros. Baja hacia la parte baja del pecho con codos cerca del torso y presiona de forma estable; evita un agarre excesivamente estrecho, muñecas dobladas o codos completamente abiertos.', 'Lie on a flat bench, set your feet and shoulder blades, and grip the bar around shoulder width. Lower it toward your lower chest with elbows close to your torso and press steadily, avoiding an excessively narrow grip, bent wrists, or fully flared elbows.'),
    ('Press Francés (Rompecráneos)', 'Acostado en banco, sostén una barra Z sobre los hombros y lleva ligeramente los brazos hacia atrás. Mantén los brazos superiores estables, flexiona los codos para acercar la barra detrás de la frente y extiende con control; evita abrir los codos o mover la carga con los hombros.', 'Lie on a bench holding an EZ bar above your shoulders and angle your upper arms slightly backward. Keep them stable, bend your elbows to lower the bar behind your forehead, and extend under control without flaring your elbows or moving the load with your shoulders.'),
    ('Press Francés con Mancuernas', 'Acostado en banco, sostén una mancuerna en cada mano sobre los hombros con palmas enfrentadas. Mantén los brazos superiores quietos, baja las cargas a los lados de la cabeza flexionando los codos y vuelve a extender; evita separar los codos o arquear la espalda.', 'Lie on a bench holding a dumbbell in each hand above your shoulders with palms facing. Keep your upper arms still, lower the weights beside your head by bending your elbows, and extend again without letting your elbows spread or arching your back.'),
    ('Tríceps en Polea', 'Colócate frente a la polea alta con postura firme y toma el accesorio elegido. Fija los codos junto al torso, extiende los antebrazos hasta contraer el tríceps y regresa lentamente manteniendo tensión; evita usar impulso, mover los hombros o apoyar el peso del cuerpo sobre la barra.', 'Stand firmly facing a high cable and hold your chosen attachment. Pin your elbows beside your torso, extend your forearms to contract the triceps, and return slowly while maintaining tension without using momentum, moving your shoulders, or leaning your body weight onto the bar.')
)
update public.exercises as exercise
set
  description = descriptions.description_es,
  description_en = descriptions.description_en
from descriptions
where exercise.user_id is null
  and lower(exercise.name) = lower(descriptions.name_es);
