with exercise_names (name_es, name_en) as (
  values
    ('Bicho Muerto (Dead Bug)', 'Dead Bug'),
    ('Crunch Abdominal Clásico', 'Classic Abdominal Crunch'),
    ('Elevación de Piernas Colgado', 'Hanging Leg Raise'),
    ('Plancha Isométrica', 'Isometric Plank'),
    ('Rueda Abdominal (Ab Wheel)', 'Ab Wheel Rollout'),
    ('Abducción en Polea o Banda', 'Cable or Band Hip Abduction'),
    ('Apertura en Máquina Abductora', 'Hip Abduction Machine'),
    ('Aductor en Máquina', 'Hip Adduction Machine'),
    ('Aductores en Máquina', 'Hip Adductors Machine'),
    ('Cierre en Máquina Aductora', 'Hip Adductor Machine'),
    ('Cuelgue Pasivo en Barra', 'Passive Bar Hang'),
    ('Curl de Muñeca Pronado', 'Pronated Wrist Curl'),
    ('Curl de Muñeca Supinado', 'Supinated Wrist Curl'),
    ('Curl Alterno con Mancuernas', 'Alternating Dumbbell Curl'),
    ('Curl de Bíceps', 'Biceps Curl'),
    ('Curl de Bíceps con Barra', 'Barbell Biceps Curl'),
    ('Curl de Bíceps en Polea con Barra Recta', 'Straight-Bar Cable Biceps Curl'),
    ('Curl de Bíceps Unilateral en Polea', 'Single-Arm Cable Biceps Curl'),
    ('Curl en Banco Inclinado con Mancuernas', 'Incline Dumbbell Curl'),
    ('Curl en Banco Scott', 'Preacher Curl'),
    ('Curl Martillo', 'Hammer Curl'),
    ('Curl Martillo con Mancuernas', 'Dumbbell Hammer Curl'),
    ('Curl Martillo en Polea con Cuerda', 'Rope Cable Hammer Curl'),
    ('Bicicleta Abdominal', 'Bicycle Crunch'),
    ('Bird Dog', 'Bird Dog'),
    ('Crunch con Peso', 'Weighted Crunch'),
    ('Crunch con Piernas en Banco', 'Bench-Supported Leg Crunch'),
    ('Crunch en Fitball', 'Stability Ball Crunch'),
    ('Crunch en máquina', 'Machine Crunch'),
    ('Crunch en polea alta', 'High Cable Crunch'),
    ('Crunch en Polea de Pie', 'Standing Cable Crunch'),
    ('Descenso Alterno de Piernas Rectas', 'Alternating Straight-Leg Lowering'),
    ('Dragon Flag', 'Dragon Flag'),
    ('Elevación de Piernas Acostado', 'Lying Leg Raise'),
    ('Elevación de piernas colgado', 'Hanging Leg Raise'),
    ('Elevación de Piernas con Empuje de Cadera', 'Leg Raise with Hip Lift'),
    ('Elevación de Piernas en Banco', 'Bench Leg Raise'),
    ('Elevación de Piernas en Silla Romana', 'Roman Chair Leg Raise'),
    ('Elevación de Rodillas Colgado', 'Hanging Knee Raise'),
    ('Elevación de rodillas en paralelas', 'Parallel Bar Knee Raise'),
    ('Empuje de Cadera Abdominal', 'Abdominal Hip Lift'),
    ('Encogimiento de Rodillas Acostado', 'Lying Knee Tuck'),
    ('Encogimiento de Rodillas Sentado', 'Seated Knee Tuck'),
    ('Frog Sit-up', 'Frog Sit-Up'),
    ('Hollow Body Hold', 'Hollow Body Hold'),
    ('Leñador en polea (Woodchoppers)', 'Cable Woodchopper'),
    ('Paseo del Granjero (Farmers Walk)', 'Farmer''s Walk'),
    ('Plancha con Elevación de Cadera', 'Plank Hip Lift'),
    ('Plancha Isométrica (Forearm Plank)', 'Forearm Plank'),
    ('Plancha Lateral', 'Side Plank'),
    ('Press Pallof', 'Pallof Press'),
    ('Rollout Abdominal con Barra', 'Barbell Ab Rollout'),
    ('Rueda abdominal (Ab Wheel)', 'Ab Wheel Rollout'),
    ('Russian Twists (Giros rusos)', 'Russian Twists'),
    ('Sit-up', 'Sit-Up'),
    ('Sit-up con Barra', 'Barbell Sit-Up'),
    ('Sit-up en Banco Declinado', 'Decline Bench Sit-Up'),
    ('Toque de Puntas con Piernas Rectas', 'Straight-Leg Toe Touch'),
    ('Toques Alternos de Talón (Alternating Heel Touch)', 'Alternating Heel Touch'),
    ('Toques de Hombro en Plancha', 'Plank Shoulder Tap'),
    ('Turkish Get Up', 'Turkish Get-Up'),
    ('Vacuum Abdominal de Pie', 'Standing Stomach Vacuum'),
    ('Estocadas', 'Lunges'),
    ('Extensión de Cuádriceps', 'Leg Extension'),
    ('Prensa (Leg Press)', 'Leg Press'),
    ('Prensa de Piernas (Leg Press)', 'Leg Press'),
    ('Sentadilla Búlgara', 'Bulgarian Split Squat'),
    ('Sentadilla Libre', 'Free-Weight Squat'),
    ('Sentadillas', 'Squats'),
    ('Sillón Cuádriceps (Leg Extension)', 'Leg Extension Machine'),
    ('Zancadas (Lunges)', 'Lunges'),
    ('Dominadas', 'Pull-Ups'),
    ('Dominadas (Pull-ups)', 'Pull-Ups'),
    ('Dorsalera', 'Lat Pulldown Machine'),
    ('Jalón al Pecho', 'Lat Pulldown'),
    ('Pullover con Mancuerna', 'Dumbbell Pullover'),
    ('Pullover en Máquina', 'Machine Pullover'),
    ('Pullover en Polea Alta', 'High Cable Pullover'),
    ('Remo con Barra', 'Barbell Row'),
    ('Remo con Barra T y Pecho Apoyado', 'Chest-Supported T-Bar Row'),
    ('Remo con Mancuernas y Pecho Apoyado', 'Chest-Supported Dumbbell Row'),
    ('Remo en Máquina con Pecho Apoyado', 'Chest-Supported Machine Row'),
    ('Remo Gironda', 'Gironda Row'),
    ('Remo Gironda (Polea Baja)', 'Low Cable Gironda Row'),
    ('Remo Pendlay en Máquina', 'Machine Pendlay Row'),
    ('Hip Thrust (Empuje de Cadera)', 'Hip Thrust'),
    ('Patada Trasera en Polea', 'Cable Glute Kickback'),
    ('Posteriores en Máquina', 'Machine Hip Extension'),
    ('Puente Glúteo Básico', 'Basic Glute Bridge'),
    ('Sentadilla Sumo', 'Sumo Squat'),
    ('Deltoides Posteriores en Máquina', 'Machine Rear Delt Fly'),
    ('Elevaciones Laterales', 'Lateral Raises'),
    ('Face Pull con Polea', 'Cable Face Pull'),
    ('Pájaros (Reverse Flyes)', 'Reverse Flyes'),
    ('Press Arnold', 'Arnold Press'),
    ('Press Militar', 'Military Press'),
    ('Press Militar con Mancuernas', 'Dumbbell Military Press'),
    ('Vuelos Laterales', 'Lateral Raises'),
    ('Camilla Isquiotibiales (Hamstring Curl)', 'Lying Hamstring Curl'),
    ('Curl de Piernas Sentado', 'Seated Leg Curl'),
    ('Curl de Piernas Tumbado', 'Lying Leg Curl'),
    ('Peso Muerto Rumano', 'Romanian Deadlift'),
    ('Sillón Isquiotibiales (Leg Curl)', 'Seated Leg Curl Machine'),
    ('Hiperextensiones', 'Back Extensions'),
    ('Supermans', 'Supermans'),
    ('Crunch Oblicuo', 'Oblique Crunch'),
    ('Elevación de Rodillas Colgado con Giro', 'Twisting Hanging Knee Raise'),
    ('Giros Rusos (Russian Twists)', 'Russian Twists'),
    ('Mountain Climber con Rotación', 'Cross-Body Mountain Climber'),
    ('Pallof', 'Pallof Press'),
    ('Press Pallof con Rotación', 'Rotational Pallof Press'),
    ('Press Pallof en Puente de Glúteos', 'Glute Bridge Pallof Press'),
    ('Press Pallof Medio Arrodillado', 'Half-Kneeling Pallof Press'),
    ('Elevación de Talones de Pie', 'Standing Calf Raise'),
    ('Elevación de Talones Sentado', 'Seated Calf Raise'),
    ('Extensión de Gemelos', 'Calf Extension'),
    ('Aperturas con Mancuernas', 'Dumbbell Fly'),
    ('Cruces en PoleaAlta', 'High Cable Crossover'),
    ('Flexiones de Pecho (Push-ups)', 'Push-Ups'),
    ('Mariposa (Pec Deck)', 'Pec Deck Fly'),
    ('Press de Banca Inclinado', 'Incline Bench Press'),
    ('Press de Banca Plano', 'Flat Bench Press'),
    ('Press Inclinado con Mancuernas', 'Incline Dumbbell Press'),
    ('Press Plano con Barra', 'Flat Barbell Bench Press'),
    ('Encogimientos (Shrugs)', 'Shrugs'),
    ('Remo al Mentón', 'Upright Row'),
    ('Extensión de Tríceps en Polea con Cuerda', 'Rope Cable Triceps Pushdown'),
    ('Extensión de Tríceps por Encima de la Cabeza con Cable', 'Overhead Cable Triceps Extension'),
    ('Extensión de Tríceps por Encima de la Cabeza con Mancuerna', 'Overhead Dumbbell Triceps Extension'),
    ('Extensión de Tríceps Unilateral en Polea', 'Single-Arm Cable Triceps Extension'),
    ('Extensión en Polea Alta', 'High Cable Triceps Pushdown'),
    ('Extensión Unilateral de Tríceps por Encima de la Cabeza', 'Single-Arm Overhead Triceps Extension'),
    ('Fondos en Banco', 'Bench Dips'),
    ('Fondos en Paralelas (Dips)', 'Parallel Bar Dips'),
    ('Patada de Tríceps', 'Triceps Kickback'),
    ('Press de Banca con Agarre Cerrado', 'Close-Grip Bench Press'),
    ('Press Francés (Rompecráneos)', 'Skull Crushers'),
    ('Press Francés con Mancuernas', 'Dumbbell Skull Crushers'),
    ('Tríceps en Polea', 'Cable Triceps Pushdown')
)
update public.exercises as exercise
set name_en = exercise_names.name_en
from exercise_names
where exercise.user_id is null
  and lower(exercise.name) = lower(exercise_names.name_es);
